### ISSUE TITLE
With FMN's new question, it is now impossible to solve Souvenir before FMN.

### ISSUE THREAD

**Issue by Blananas2** [Timwi/KtaneSouvenir#105]
With the way FMN's new question is implemented, which is to wait until FMN is solved before generating the question, we can no longer solve the two modules in either order, even if you toggle the "Exclude ignored modules" mod setting (as shown below). If instead the question was generated once FMN is in submission mode, this would resolve the issue.

Relevant logfile: https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=5393421aea281e0fe2d90983e51e40206fdf3fac;bomb=IW6EF0

**Comment by Timwi** [comment]
Thanks for letting us know. We’ve disabled FMN, FAC and FTC for the time being and will update Souvenir with a whole brand-new implementation that doesn’t have this issue.
